### PR TITLE
[NO-ISSUE] update cockroach db version to v20.1.6

### PR DESCRIPTION
**Pull request by dsupure**
**Summary of changes:**
* update cockroach db version to v20.1.6

### CODE REVIEW

**Review by haibinxie — APPROVED** [review]

**Review by Pure-AdamuKaapan — APPROVED** [review]
LGTM, on the requirement that we test an upgrade before we push a release.

**Comment by StuartWhelan** [comment]
Will you be including instructions on how to upgrade to this version on already running clusters?

**Review by DIMPLY — APPROVED** [review]
LGTM

**Review by sdodsley — CHANGES_REQUESTED** [review]
👍 on the upgrade process requirment before we do this version upgrade.

**Comment by haibinxie** [comment]
@dsupure since this version also has memory leak, i suggest set default memory limit to 1GB. Although i think a less memory limit should be set, if there is enough test showing 512MB is sufficient. In theory our metadata should be much less than that.

**Comment by mscbpi** [comment]
Cockroach says it, it is not a leak and the way we mention it can lead to confusion. It just grows with with available memory until reaching a threshold that we might set with resources.memory.limits.

**Comment by dsupure** [comment]
Withdraw this PR since it's not the actual memory leaking.

**Pull request closed without merging**
