### PR TITLE
[NO-ISSUE] Add configmap to node-server pods

### PR DESCRIPTION
**Pull request by dsupure**
**Summary of changes:** 
 * Add config map to node-server pods.

### CODE REVIEW

**Comment by dsupure** [comment]
> please don't forget to run a CI to verify.

sure.

**Comment by Pure-AdamuKaapan** [comment]
@dsupure (or anyone else): has CI been run on this yet? (AKA is it mergeable?)

**Comment by pure-jliao** [comment]
bump up this PR, forgot to merge this one? @dsupure

**Comment by dsupure** [comment]
Ah, I created this one day before my parental leave. It was testing fine. We can merge it.

**Comment by Pure-AdamuKaapan** [comment]
Oh funny, and I just added it to the controller server. Sweet!

**Pull request merged**
