### PR TITLE
Add feature list

### PR DESCRIPTION
**Pull request by haibinxie**
Use image because markdown file does not support split-cell.

### CODE REVIEW

**Review by Pure-AdamuKaapan — CHANGES_REQUESTED** [review]
Please remove the .DS_Store file that got added (ugh macOS)

**Review by Pure-AdamuKaapan — COMMENTED** [review]
A couple other nits on the feature list image since I can't leave a direct comment:
* Typo in "Complinace" (fix to "Compliance")
* Typo in "Contoller" (fix to "Controller")
* [nit] Make sure the spacing is consistent after the `Y` in the Volume Snapshot row
* [nit] capitalize "options" in "FS Mount and Create options"

**Comment by sdodsley** [comment]
A couple of points from me...

Please remove the reference to REST 2 - this is an internal-only thing and customers need not be aware of it and may raise questions...
For all features that are FA or FB only, please ensure these are identified. For example, NFS v4.1 is FB only. If you leave it as just a Y then people may expect FA-Files to be included for FA...

**Comment by haibinxie** [comment]
@Pure-AdamuKaapan @sdodsley thanks, updated.

**Review by Pure-AdamuKaapan — COMMENTED** [review]
On Simon's note of the FA/FB split, a couple more to split up:
* Snapshot import should be split and have N for FB (since we don't support FB snapshots)
* QoS Support should be split and have N for FB, I believe QoS is FA-only at the moment

**Comment by haibinxie** [comment]
@Pure-AdamuKaapan nice catch, updated.

**Review by sdodsley — APPROVED** [review]

**Review by Pure-AdamuKaapan — APPROVED** [review]
LGTM! Thanks for making this, looks really nice.

**Pull request merged**
