### PR TITLE
[NO-ISSUE] Updated documents after install feedback

### PR DESCRIPTION
**Pull request by Pure-AdamuKaapan**
* Removed empty "arrays" section as it conflicts with commented example
  * @sdodsley I'd like some feedback on if you think this is correct or not. I can see valid reasons for commenting it out (like if you're the type of person to uncomment examples and change them), and valid reasons to keep the empty `arrays` entries (like if you're the kind of person to copy from examples but leave them commented).
* Added debugging info for taints and tolerations
* Fixed incorrect NFSEndpoint capitalization in examples
* Added an example `install` command to the basic install section

### CODE REVIEW

**Comment by Pure-AdamuKaapan** [comment]
Whoops, dunno how I missed that. Lemme do a deeper search for lowercase NFS endpoint and catch all of them.

**Comment by Pure-AdamuKaapan** [comment]
@sdodsley the rest of the NFS endpoints have been fixed

**Comment by sdodsley** [comment]
@Pure-AdamuKaapan I don't think so... values.yaml - line 32

**Comment by Pure-AdamuKaapan** [comment]
Heads up, I did a quick test and removing the `arrays` default is making a bit easier to mess up the install (it'll complain if you don't add both the `FlashArray` and `FlashBlade` keys), so I'll probably add it back in.

**Pull request merged**
