### PR TITLE
Add more OpenShift installation details

### PR DESCRIPTION
**Pull request by sdodsley**
Add more details for successful OpenShift installation

### CODE REVIEW

**Review by Pure-AdamuKaapan — CHANGES_REQUESTED** [review]
Looks like line 110 got split on accident? Should probably all be on the same line.

On a related note, is it not possible to define this in a file in the chart? I know we ran into this with a different SCC and we added a file to fix it, no command necessary.

**Comment by sdodsley** [comment]
If we can add it to the chart then great,
I deliberately split line 110 so it was more obvious

**Comment by Pure-AdamuKaapan** [comment]
@sdodsley I see we have https://github.com/purestorage/pso-csi/blob/master/pure-pso/templates/plugin/scc.yaml#L14-L15, which should allow privileged containers, and we have it assigned to the proper service account.

**Comment by sdodsley** [comment]
This was not a problem with OpenShift 4.6, but 4.7 seems to require this manual command again

**Comment by dsupure** [comment]
@sdodsley: Do you want to merge this one?

**Review by dsupure — APPROVED** [review]
LGTM!

**Pull request merged**
